### ISSUE TITLE
Suggetion: How to do simillar steps via docker-compose

### ISSUE THREAD

**Issue by vikrant-pawar-exa** [JAORMX/JAORMX.github.io#7]
Hi, 
Nice article wanted same mount commands via docker-compose, 
Do you have any links for those

I'm referring to https://jaosorior.dev/2018/selinux-and-docker-notes/ this page

**Comment by JAORMX** [comment]
I don't unfortunately. I don't use docker-compose in my day to day :/ If you figure that out, I could include it in the blog post and give you credit there.
